"""
test_pdf_parser.py — Tests for the generic PDF parser.

Run with:
    python -m pytest tests/test_pdf_parser.py -v

The PDF fixtures are generated by tests/fixtures/create_pdf_fixtures.py.
Run that script once if the fixtures don't exist yet.
"""

from datetime import date
from pathlib import Path

import pytest

from src.parsers.pdf_parser import PDFParser

FIXTURES = Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def get_parser(filename: str, bank_name: str = "GENERIC") -> PDFParser:
    """Return a PDFParser pointed at a fixture file."""
    path = FIXTURES / filename
    if not path.exists():
        pytest.skip(f"PDF fixture not found: {filename}. Run create_pdf_fixtures.py first.")
    return PDFParser(file_path=str(path), bank_name=bank_name)


# ---------------------------------------------------------------------------
# Table-mode PDF (embedded table)
# ---------------------------------------------------------------------------

class TestPDFParserTableMode:

    def setup_method(self):
        self.parser = get_parser("sample_table_pdf.pdf")

    def test_returns_correct_transaction_count(self):
        transactions = self.parser.parse()
        assert len(transactions) == 8

    def test_debit_transaction_parsed_correctly(self):
        transactions = self.parser.parse()
        shopee = next(t for t in transactions if "SHOPEE" in t.description)
        assert shopee.debit_amount == 250.00
        assert shopee.credit_amount == 0.0
        assert shopee.transaction_date == date(2026, 3, 3)

    def test_credit_transaction_parsed_correctly(self):
        transactions = self.parser.parse()
        salary = next(t for t in transactions if "SALARY" in t.description and "BONUS" not in t.description)
        assert salary.credit_amount == 3500.00
        assert salary.debit_amount == 0.0

    def test_balance_parsed_correctly(self):
        transactions = self.parser.parse()
        shopee = next(t for t in transactions if "SHOPEE" in t.description)
        assert shopee.balance == 4750.00

    def test_reference_extracted_from_description(self):
        transactions = self.parser.parse()
        tnb = next(t for t in transactions if "TNB" in t.description)
        assert tnb.reference == "TT123456"

    def test_account_number_extracted(self):
        account = self.parser.extract_account_number()
        assert account == "1234567890"

    def test_statement_period_extracted(self):
        start, end = self.parser.extract_statement_period()
        assert start == date(2026, 3, 1)
        assert end == date(2026, 3, 31)

    def test_no_duplicate_hashes(self):
        transactions = self.parser.parse()
        hashes = [t.compute_hash() for t in transactions]
        assert len(hashes) == len(set(hashes))

    def test_all_transactions_have_descriptions(self):
        transactions = self.parser.parse()
        for txn in transactions:
            assert txn.description, f"Transaction on {txn.transaction_date} has empty description"


# ---------------------------------------------------------------------------
# Text-mode PDF (plain text lines, no tables)
# ---------------------------------------------------------------------------

class TestPDFParserTextMode:

    def setup_method(self):
        self.parser = get_parser("sample_text_pdf.pdf")

    def test_returns_transactions(self):
        transactions = self.parser.parse()
        # Text mode should find at least some transactions
        assert len(transactions) > 0

    def test_dates_parsed_correctly(self):
        transactions = self.parser.parse()
        dates = [t.transaction_date for t in transactions]
        assert date(2026, 3, 3) in dates

    def test_salary_classified_as_credit(self):
        transactions = self.parser.parse()
        salary = next(
            (t for t in transactions if "SALARY" in t.description), None
        )
        if salary:
            # SALARY keyword should trigger credit classification
            assert salary.credit_amount > 0
            assert salary.debit_amount == 0.0

    def test_account_number_extracted(self):
        account = self.parser.extract_account_number()
        assert account == "9876543210"

    def test_statement_period_extracted(self):
        start, end = self.parser.extract_statement_period()
        assert start == date(2026, 3, 1)
        assert end == date(2026, 3, 31)


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------

class TestPDFParserErrors:

    def test_raises_on_missing_file(self):
        with pytest.raises(FileNotFoundError):
            PDFParser(file_path="/nonexistent/path/statement.pdf", bank_name="CIMB")
